%% -------------------------------------------------------------------
%%
%% Copyright (c) 2013-2017 Basho Technologies, Inc.
%% Copyright (c) 2023-2024 Workday, Inc.
%%
%% This file is provided to you under the Apache License,
%% Version 2.0 (the "License"); you may not use this file
%% except in compliance with the License.  You may obtain
%% a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.
%%
%% -------------------------------------------------------------------
%%
%% @doc External named validators for schema writers.
%%
-module(cuttlefish_validators).

% Predefined Validators
-export([
    integer_compare/2,
    integer_range/2,
    ip_address/0,
    kilobyte_range/2,
    kiloword_range/2,
    named/1,
    non_neg_integer/0,
    port_number/0,
    pos_integer/0,
    power_of_two/0,
    schedulers_combined/0,
    schedulers_percent/0,
    schedulers_online/0,
    schedulers_total/0,
    wordsize_multiple/0,
    wordsize_range/2
]).

% Public API
-export([
    %% This list is baked into the code in the ?CANNED_EXCLUDE definition.
    integer_value/1
]).

% Private API
-export([
    %% This list is baked into the code in the ?CANNED_EXCLUDE definition.
    canned_validators/0,
    resolve_validators/3
]).

% API Types
-export_type([
    badarg_error/0,
    compare_op/0,
    func_args/0,
    func_name/0,
    integer_const/0,
    validator/0,
    validators/0
]).

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").
-endif.

-type badarg_error() :: {badarg, {module(), func_name(), func_args()}}.
-type compare_op() :: eq | ne | lt | le | gt | ge | mult.
-type func_args() :: list(term()).
-type func_name() :: atom().
-type integer_const() :: integer() |
    cpus_count | cpus_online | cpus_avail | kilobyte | kiloword | wordsize.
-type validator() :: cuttlefish_validator:validator().
-type validators() :: list(cuttlefish_validator:validator()).

-define(BADARG(Args), {badarg, {?MODULE, ?FUNCTION_NAME, Args}}).
-define(CANNED_EXCLUDE, [
    {canned_validators, 0},
    {integer_value, 1},
    {resolve_validators, 3}
]).

%% ===================================================================
%% Predefined Validator Generators
%% ===================================================================

-spec integer_compare(
    Op :: compare_op(), Val :: integer_const() )
        -> validator() | badarg_error().
%% @doc Generate a validator for the specified comparison.
%%
%% The name of the generated validator is derived from the comparison
%% operator and value (after resolution of symbolic constants).
%% For example, the validator generated by 'integer_compare(ge, 42)'
%% would be named "integer:&gt;=42".
integer_compare(Op, Val) ->
    case integer_value(Val) of
        V when erlang:is_integer(V) ->
            integer_compare(Op, V, erlang:integer_to_list(V));
        E ->
            E
    end.

-spec integer_range(
    Lo :: integer_const(), Hi :: integer_const() )
        -> validator() | badarg_error().
%% @doc Generate a validator for the specified range.
%%
%% The name of the generated validator is "integer:&lt;Lo&gt;..&lt;Hi&gt;"
%% (after resolution of symbolic constants).
%% @end
%% Recognize some common ranges built with literals.
integer_range(0, 65535) ->
    F = fun(V) ->
        erlang:is_integer(V) andalso V >= 0 andalso V =< 65535
    end,
    {validator, "integer:0..65535",
        "must be an integer in the range 0..65535", F};
integer_range(1024, 134217727) ->
    F = fun(V) ->
        erlang:is_integer(V) andalso V >= 1024 andalso V =< 134217727
    end,
    {validator, "integer:1024..134217727",
        "must be an integer in the range 1024..134217727", F};
%% Handle arbitrary integers.
integer_range(Lo, Hi) when erlang:is_integer(Lo), erlang:is_integer(Hi) ->
    if
        Lo =< Hi ->
            F = fun(V) ->
                erlang:is_integer(V) andalso V >= Lo andalso V =< Hi
            end,
            R = lists:concat([Lo, "..", Hi]),
            N = "integer:" ++ R,
            D = "must be an integer in the range " ++ R,
            {validator, N, D, F};
        true ->
            ?BADARG([Lo, Hi])
    end;
%% Handle symbolic constants.
integer_range(Lo, Hi)
        when (erlang:is_integer(Lo) orelse erlang:is_atom(Lo))
        andalso (erlang:is_integer(Hi) orelse erlang:is_atom(Hi)) ->
    L = integer_value(Lo),
    H = integer_value(Hi),
    if
        erlang:is_integer(L) andalso erlang:is_integer(H) ->
            integer_range(L, H);
        true ->
            ?BADARG([Lo, Hi])
    end;
integer_range(Lo, Hi) ->
    ?BADARG([Lo, Hi]).

-spec ip_address() -> validator().
%% @doc Generate a validator for the 'inet:ip_address()' type.
%%
%% The name of the generated validator is "ip-address".
ip_address() ->
    F = fun(Str) ->
        erlang:element(1, inet:parse_strict_address(Str)) =:= ok
    end,
    {validator, "ip-address",
        "must be a valid IPv4 or IPv6 address", F}.

-spec kilobyte_range(
    Lo :: integer(), Hi :: integer() )
        -> validator() | badarg_error().
%% @doc Generate a validator for the specified range scaled to kilobytes.
%%
%% The name of the generated validator is "bytesize:&lt;Lo&gt;KB..&lt;Hi&gt;KB".
kilobyte_range(Lo, Hi) when
        erlang:is_integer(Lo), erlang:is_integer(Hi), Lo =< Hi ->
    L = (Lo * 1024),
    H = (Hi * 1024),
    F = fun(V) ->
        erlang:is_integer(V) andalso V >= L andalso V =< H
    end,
    R = lists:concat([Lo, "KB..", Hi, "KB"]),
    N = "bytesize:" ++ R,
    D = "must be in the range " ++ R,
    {validator, N, D, F};
kilobyte_range(Lo, Hi) ->
    ?BADARG([Lo, Hi]).

-spec kiloword_range(
    Lo :: integer(), Hi :: integer() )
        -> validator() | badarg_error().
%% @doc Generate a validator for the specified range scaled to kilowords.
%% @equiv kilobyte_range(Lo * integer_value(wordsize), Hi * integer_value(wordsize))
kiloword_range(Lo, Hi) when
        erlang:is_integer(Lo), erlang:is_integer(Hi), Lo =< Hi ->
    Mult = integer_value(wordsize),
    kilobyte_range(Lo * Mult, Hi * Mult);
kiloword_range(Lo, Hi) ->
    ?BADARG([Lo, Hi]).

-spec named(
    ValidatorName :: nonempty_string() )
        -> validator() | badarg_error().
%% @doc Generate the specified predefined validator.
named("integer:>0") ->
    pos_integer();
named("integer:>=0") ->
    non_neg_integer();
named("ip-address") ->
    ip_address();
named("non-neg-integer") ->
    non_neg_integer();
named("port-number") ->
    port_number();
named("pos-integer") ->
    pos_integer();
named("integer:0..65535") ->
    integer_range(0, 65535);
named("power-of-two") ->
    power_of_two();
named("schedulers-combined") ->
    schedulers_combined();
named("schedulers-percent") ->
    schedulers_percent();
named("schedulers-online") ->
    schedulers_online();
named("schedulers-total") ->
    schedulers_total();
named("wordsize-divisible") ->
    wordsize_multiple();
named("wordsize-multiple") ->
    wordsize_multiple();
named(VName) ->
    ?BADARG([VName]).

-spec non_neg_integer() -> validator().
%% @doc Generate a validator for the 'erlang:non_neg_integer()' type.
%% @equiv integer_compare(ge, 0)
non_neg_integer() ->
    integer_compare(ge, 0).

-spec port_number() -> validator().
%% @doc Generate a validator for the 'inet:port_number()' type.
%% @equiv integer_range(0, 65535)
port_number() ->
    integer_range(0, 65535).

-spec pos_integer() -> validator().
%% @doc Generate a validator for the 'erlang:pos_integer()' type.
%% @equiv integer_compare(gt, 0)
pos_integer() ->
    integer_compare(gt, 0).

-spec power_of_two() -> validator().
%% @doc Generate a validator for non-negative integral powers of 2.
%%
%% The name of the generated validator is "power-of-two".
power_of_two() ->
    F = fun(V) ->
        erlang:is_integer(V) andalso V >= 0 andalso (V band (V - 1)) =:= 0
    end,
    {validator, "power-of-two", "must be an integral power of two", F}.

-spec schedulers_combined() -> validator().
%% @doc Generate a validator for the 'string' value of the '+S' emulator flag.
%%
%% The name of the generated validator is "scheduler-combined".
schedulers_combined() ->
    CpuCount = integer_value(cpus_count),
    MinCount = if CpuCount < 2 -> 0; true -> (0 - CpuCount + 1) end,
    CpuAvail = integer_value(cpus_avail),
    MinAvail = if CpuAvail < 2 -> 0; true -> (0 - CpuAvail + 1) end,
    F = fun
        ([_|_] = Str) ->
            {Tot, Onl} = case string:split(Str, ":", all) of
                %% It appears that almost any number of trailing colons, with
                %% or without intervening numbers, are allowed and ignored on
                %% the command-line, but we're enforcing the documented
                %% parameter pattern.
                [[_|_] = TotStr] ->
                    {scheduler_string_value(TotStr), 0};
                [[_|_] = TotStr, []] ->
                    {scheduler_string_value(TotStr), 0};
                [[], [_|_] = OnlStr] ->
                    {0, scheduler_string_value(OnlStr)};
                [[_|_] = TotStr, [_|_] = OnlStr] ->
                    {scheduler_string_value(TotStr), scheduler_string_value(OnlStr)};
                _ ->
                    {false, false}
            end,
            if
                Tot =:= false orelse Onl =:= false ->
                    false;
                true ->
                    EffTot = if Tot < 0 -> (Tot + CpuCount); true -> Tot end,
                    EffOnl = if Onl < 0 -> (Onl + CpuAvail); true -> Onl end,
                    EffOnl > 0 andalso EffTot >= EffOnl
            end;
        (_) ->
            false
    end,
    D = lists:concat([
        "must be 'Total', 'Total:Online', or ':Online' when Total is in the"
        " range ", MinCount, "..1024, Online is in the range ",
        MinAvail, "..1024, and effective Total >= effective Online."
    ]),
    {validator, "schedulers-combined", D, F}.

-spec schedulers_percent() -> validator().
%% @doc Generate a validator for the 'string' value of the '+SP' emulator flag.
%%
%% The name of the generated validator is "scheduler-percent".
schedulers_percent() ->
    F = fun
        ([_|_] = Str) ->
            case string:split(Str, ":", all) of
                %% It appears that almost any number of trailing colons, with
                %% or without intervening numbers, are allowed and ignored on
                %% the command-line, but we're enforcing the documented
                %% parameter pattern.
                [[_|_] = TotStr] ->
                    string_percent_check(TotStr);
                [[_|_] = TotStr, []] ->
                    string_percent_check(TotStr);
                [[], [_|_] = OnlStr] ->
                    string_percent_check(OnlStr);
                [[_|_] = TotStr, [_|_] = OnlStr] ->
                    string_percent_check(TotStr) andalso string_percent_check(OnlStr);
                _ ->
                    false
            end;
        (_) ->
            false
    end,
    D = "must be 'Total', 'Total:Online', or ':Online' when Total and Online"
        " are each in the range 1..100",
    {validator, "schedulers-percent", D, F}.

-spec schedulers_online() -> validator().
%% @doc Generate a validator for the SchedulerOnline integer component of the
%% '+S' emulator flag.
%%
%% The name of the generated validator is "schedulers-online".
schedulers_online() ->
    Cnt = integer_value(cpus_avail),
    Min = if Cnt < 2 -> 0; true -> (0 - Cnt + 1) end,
    F = fun(V) ->
        erlang:is_integer(V) andalso V >= Min andalso V =< 1024
    end,
    D = lists:concat(["must be an integer in the range ", Min, "..1024"]),
    {validator, "schedulers-online", D, F}.

-spec schedulers_total() -> validator().
%% @doc Generate a validator for the Schedulers integer component of the
%% '+S' emulator flag.
%%
%% The name of the generated validator is "schedulers-total".
schedulers_total() ->
    Cnt = integer_value(cpus_count),
    Min = if Cnt < 2 -> 0; true -> (0 - Cnt + 1) end,
    F = fun(V) ->
        erlang:is_integer(V) andalso V >= Min andalso V =< 1024
    end,
    D = lists:concat(["must be an integer in the range ", Min, "..1024"]),
    {validator, "schedulers-total", D, F}.

-spec wordsize_multiple() -> validator().
%% @doc Generate a validator for whole multiples of wordsize.
%%
%% The name of the generated validator is "wordsize-multiple".
wordsize_multiple() ->
    Key = {?MODULE, ?FUNCTION_NAME},
    case erlang:get(Key) of
        Val when erlang:is_tuple(Val) ->
            Val;
        _ ->
            W = integer_value(wordsize),
            S = erlang:integer_to_list(W),
            F = fun(V) ->
                erlang:is_integer(V) andalso (V rem W) =:= 0
            end,
            Res = {validator, "wordsize-multiple",
                    "must be an integer exactly divisible by " ++ S, F},
            erlang:put(Key, Res),
            Res
    end.

-spec wordsize_range(
    Lo :: integer(), Hi :: integer() )
        -> validator() | badarg_error().
%% @doc Generate a validator for the specified range scaled to words.
%% @equiv integer_range(Lo * integer_value(wordsize), Hi * integer_value(wordsize))
wordsize_range(Lo, Hi) when
        erlang:is_integer(Lo), erlang:is_integer(Hi), Lo =< Hi ->
    Mult = integer_value(wordsize),
    integer_range(Lo * Mult, Hi * Mult);
wordsize_range(Lo, Hi) ->
    ?BADARG([Lo, Hi]).

%% ===================================================================
%% Public API
%% ===================================================================

-spec integer_value(
    Val :: integer_const() )
        -> integer() | badarg_error().
%% @doc Resolve a (possibly symbolic) integral value.
%%
%% Unless Val is an unrecognized symbolic constant, the result is always an
%% integer, even if the underlying erlang:system_info/1 call is allowed to
%% return a non-integral value.
%% Values obtained via non-trivial system calls and/or calculations are cached.
%%
%% Validators or translations can use this function to transparently map
%% integers and symbolic constants to known-valid integers efficiently.
%%
%% The recognized symbolic constants are:
%% <dl><dt>'cpus_count'</dt><dd>
%%  The number of logical processors (LCPUs) configured in the system, or '1'
%%  if the number cannot be determined.<br/>
%%  See <a
%%  href="https://www.erlang.org/doc/apps/erts/erlang#system_info_logical_processors"
%%  target="_blank">erlang:system_info(logical_processors)</a>
%% </dd><dt>'cpus_online'</dt><dd>
%%  The number of logical processors (LCPUs) online in the system, or the value
%%  of 'cpus_count' if the number cannot be determined.<br/>
%%  Always &lt;= 'cpus_count'.<br/>
%%  See <a
%%  href="https://www.erlang.org/doc/apps/erts/erlang#system_info_logical_processors_online"
%%  target="_blank">erlang:system_info(logical_processors_online)</a>
%% </dd><dt>'cpus_avail'</dt><dd>
%%  The number of logical processors (LCPUs) available in the system, which
%%  <em>MAY</em> be constrained by a CPU quota in effect, or the value of
%%  'cpus_online' if the number cannot be determined.<br/>
%%  Always &lt;= 'cpus_online'.<br/>
%%  See <a
%%  href="https://www.erlang.org/doc/apps/erts/erlang#system_info_logical_processors_available"
%%  target="_blank">erlang:system_info(logical_processors_available)</a><br/>
%%  See <a
%%  href="https://www.erlang.org/doc/apps/erts/erlang#system_info_cpu_quota"
%%  target="_blank">erlang:system_info(cpu_quota)</a>
%% </dd><dt>'kiloword'</dt><dd>
%%  'wordsize' x 1024.
%% </dd><dt>'wordsize'</dt><dd>
%%  The size of an emulator term word, in bytes.
%%  In nearly all cases, this is the CPU word (pointer) size.<br/>
%%  See <a
%%  href="https://www.erlang.org/doc/apps/erts/erlang#system_info_wordsize"
%%  target="_blank">erlang:system_info({wordsize, external})</a>
%% </dd></dl>
integer_value(CpuKey) when
        CpuKey =:= cpus_count; CpuKey =:= cpus_online; CpuKey =:= cpus_avail ->
    Key = {?MODULE, ?FUNCTION_NAME, CpuKey},
    case erlang:get(Key) of
        Val when erlang:is_integer(Val) ->
            Val;
        _ ->
            V = case CpuKey of
                cpus_avail ->
                    A = erlang:system_info(logical_processors_available),
                    Q = erlang:system_info(cpu_quota),
                    if
                        erlang:is_integer(Q) ->
                            if
                                erlang:is_integer(A) ->
                                    if
                                        Q < A ->
                                            Q;
                                        true ->
                                            A
                                    end;
                                true ->
                                    Q
                            end;
                        erlang:is_integer(A) ->
                            A;
                        true ->
                            integer_value(cpus_online)
                    end;
                cpus_online ->
                    O = erlang:system_info(logical_processors_online),
                    if
                        erlang:is_integer(O) ->
                            O;
                        true ->
                            integer_value(cpus_count)
                    end;
                _ ->
                    C = erlang:system_info(logical_processors),
                    if
                        erlang:is_integer(C) ->
                            C;
                        true ->
                            1
                    end
            end,
            erlang:put(Key, V),
            V
    end;
integer_value(kilobyte) ->
    1024;
integer_value(kiloword) ->
    io:format(user, "~n~ts:~ts:~b~n", [?MODULE, ?FUNCTION_NAME, ?LINE]),
    integer_value(wordsize) * 1024;
integer_value(wordsize) ->
    io:format(user, "~n~ts:~ts:~b~n", [?MODULE, ?FUNCTION_NAME, ?LINE]),
    Key = {?MODULE, ?FUNCTION_NAME, wordsize},
    case erlang:get(Key) of
        Val when erlang:is_integer(Val) ->
            Val;
        _ ->
            V = erlang:system_info({wordsize, external}),
            erlang:put(Key, V),
            V
    end;
integer_value(Val) when erlang:is_integer(Val) ->
    Val;
integer_value(Val) ->
    ?BADARG([Val]).

%% ===================================================================
%% Private API
%% ===================================================================

-spec canned_validators() -> list({atom(), arity()}).
%% @private
%% @doc Returns the list of predefined validators as a list of
%% {FuncName, FuncArity} tuples.
canned_validators() ->
    maps:keys(canned()).

-spec resolve_validators(
    Proplist :: proplists:proplist(),
    Validators :: validators(),
    Errors :: list(cuttlefish_error:error()) )
        -> {proplists:proplist(), validators(), list(cuttlefish_error:error())}.
%% @private
%% @doc Resolve predefined validators in Proplist, updating Proplist and Validators.
resolve_validators(Proplist, Validators, Errors) ->
    case proplists:get_value(validators, Proplist, []) of
        [_|_] = ValSpecs ->
            {ValNames, ValidatorsOut, ErrorsOut} =
                resolve_validators(ValSpecs, [], Validators, Errors, canned()),
            ProplistOut = lists:keystore(
                validators, 1, Proplist, {validators, ValNames}),
            {ProplistOut, ValidatorsOut, ErrorsOut};
        _ ->
            {Proplist, Validators, Errors}
    end.

%% ===================================================================
%% Internal
%% ===================================================================

-type canned() :: #{{func_name(), arity()} => []}.
-type val_name() :: nonempty_string().
-type val_spec() :: val_name() | func_name() | {func_name(), func_args()}.

-spec canned() -> canned().
%% @hidden
%% @doc Returns the set of predefined validator functions.
canned() ->
    Key = {?MODULE, ?FUNCTION_NAME},
    case erlang:get(Key) of
        Val when erlang:is_map(Val) ->
            Val;
        _ ->
            Exports = module_info(exports),
            Exclude = [{module_info, 0}, {module_info, 1} | ?CANNED_EXCLUDE],
            Canned = maps:from_keys(Exports -- Exclude, []),
            erlang:put(Key, Canned),
            Canned
    end.

-spec integer_compare(
    Op :: compare_op(), Val :: integer(), VStr :: nonempty_string() )
        -> validator() | badarg_error().
%% @hidden
%% @doc Integer comparators from resolved integer_compare/2 parameters.
integer_compare(eq, Val, S) ->
    F = fun(V) -> V =:= Val end,
    {validator, "integer:==" ++ S, "must be an integer == " ++ S, F};
integer_compare(ge, Val, S) ->
    F = fun(V) -> erlang:is_integer(V) andalso V >= Val end,
    {validator, "integer:>=" ++ S, "must be an integer >= " ++ S, F};
integer_compare(gt, Val, S) ->
    F = fun(V) -> erlang:is_integer(V) andalso V > Val end,
    {validator, "integer:>" ++ S, "must be an integer > " ++ S, F};
integer_compare(le, Val, S) ->
    F = fun(V) -> erlang:is_integer(V) andalso V =< Val end,
    {validator, "integer:<=" ++ S, "must be an integer <= " ++ S, F};
integer_compare(lt, Val, S) ->
    F = fun(V) -> erlang:is_integer(V) andalso V < Val end,
    {validator, "integer:<" ++ S, "must be an integer < " ++ S, F};
integer_compare(mult, Val, S) ->
    F = fun(V) -> erlang:is_integer(V) andalso (V rem Val) =:= 0 end,
    {validator, "integer:mult" ++ S,
        "must be an integer evenly divisible by " ++ S, F};
integer_compare(ne, Val, S) ->
    F = fun(V) -> erlang:is_integer(V) andalso V =/= Val end,
    {validator, "integer:!=" ++ S, "must be an integer != " ++ S, F};
integer_compare(Op, _Val, _VStr) ->
    ?BADARG([Op]).

-spec resolve_validators(
    ValSpecs :: list(val_spec()),
    ValNames :: list(val_name()),
    Validators :: validators(),
    Errors :: list(cuttlefish_error:error()),
    Canned :: canned() )
        -> {list(val_name()), validators(), list(cuttlefish_error:error())}.
%% @hidden
%% @doc Resolve predefined validators in ValSpecs.
resolve_validators([Func | ValSpecs], ValNames, Validators, Errors, Canned)
        when erlang:is_atom(Func)
        andalso erlang:is_map_key({Func, 0}, Canned) ->
    %% Arity zero generators always return a valid constant validator spec.
    {validator, ValName, _, _} = ValSpec = ?MODULE:Func(),
    resolve_validators(
        ValSpecs, [ValName | ValNames],
        cuttlefish_validator:parse_and_merge(ValSpec, Validators),
        Errors, Canned);
resolve_validators(
    [{Func, Args} | ValSpecs], ValNames, Validators, Errors, Canned)
        when erlang:is_atom(Func) andalso erlang:is_list(Args)
        andalso erlang:is_map_key({Func, erlang:length(Args)}, Canned) ->
    case erlang:apply(?MODULE, Func, Args) of
        {validator, ValName, _, _} = ValSpec ->
            resolve_validators(
                ValSpecs, [ValName | ValNames],
                cuttlefish_validator:parse_and_merge(ValSpec, Validators),
                Errors, Canned);
        BadArg ->
            Error = {error, {validator_parse, BadArg}},
            resolve_validators(
                ValSpecs, ValNames, Validators, [Error | Errors], Canned)

    end;
resolve_validators([ValName | ValSpecs], ValNames, Validators, Errors, Canned) ->
    resolve_validators(ValSpecs, [ValName | ValNames], Validators, Errors, Canned);
resolve_validators([], ValNames, Validators, Errors, _Canned) ->
    {lists:reverse(ValNames), Validators, lists:reverse(Errors)}.

-spec scheduler_string_value(Str :: nonempty_string() ) -> integer() | false.
scheduler_string_value(Str) ->
    case string:to_integer(Str) of
        {I, []} when I =< 1024 ->
            I;
        _ ->
            false
    end.

-spec string_percent_check(Str :: nonempty_string() ) -> boolean().
string_percent_check(Str) ->
    case string:to_integer(Str) of
        {I, []} ->
            I >= 1 andalso I =< 100;
        _ ->
            false
    end.

%% ===================================================================
%% EUnit Tests
%% ===================================================================
%%
%% Note that when TEST is defined the canned() set will include exports added
%% by EUnit, so don't make any assumptions about its size.
%%
-ifdef(TEST).

cache_test() ->
    D1 = erlang:get(),
    F1 = canned(),
    C1 = integer_value(cpus_count),
    W1 = integer_value(wordsize),
    V1 = wordsize_multiple(),
    D2 = erlang:get(),
    F2 = canned(),
    C2 = integer_value(cpus_count),
    W2 = integer_value(wordsize),
    V2 = wordsize_multiple(),
    D3 = erlang:get(),
    ?assertNotEqual(D1, D2),
    ?assertEqual(D2, D3),
    ?assertEqual(F1, F2),
    ?assertEqual(C1, C2),
    ?assertEqual(W1, W2),
    ?assertEqual(V1, V2).

parse_test() ->
    Val = power_of_two(),
    Alts = [
        {validator, power_of_two},
        {validator, power_of_two, []},
        {validator, named, ["power-of-two"]}
    ],
    _ = [?assertEqual(Val, cuttlefish_validator:parse(Alt)) || Alt <- Alts].

error_test() ->
    ?assertMatch(
        {validator, _, _, _},
        integer_range(5, 7)),
    ?assertMatch(
        {badarg, {?MODULE, integer_range, [7, 5]}},
        integer_range(7, 5)),
    ?assertMatch(
        {error, {validator_parse, {badarg, {?MODULE, integer_range, [7, 5]}}}},
        cuttlefish_validator:parse({validator, integer_range, [7, 5]})),
    ?assertMatch(
        {validator, _, _, _},
        cuttlefish_validator:parse({validator, power_of_two})),
    ?assertMatch(
        {error, {validator_parse, {undefined, {?MODULE, power_of_two, [5]}}}},
        cuttlefish_validator:parse({validator, power_of_two, [5]})).

integer_range_test() ->
    RV = integer_range(-7, 12),
    ?assertMatch(
        {validator, "integer:-7..12", _, F} when erlang:is_function(F, 1), RV),
    RF = erlang:element(4, RV),
    ?assertMatch(false, RF(-8)),
    ?assertMatch(true,  RF(-7)),
    ?assertMatch(true,  RF(-6)),
    ?assertMatch(true,  RF(11)),
    ?assertMatch(true,  RF(12)),
    ?assertMatch(false, RF(13)).

integer_value_test() ->
    _ = [?assertMatch(I when erlang:is_integer(I), integer_value(C), C)
        || C <- [cpus_count, cpus_online, cpus_avail, kiloword, wordsize]],
    ?assert(integer_value(cpus_avail) =< integer_value(cpus_online)),
    ?assert(integer_value(cpus_online) =< integer_value(cpus_count)),
    ?assert(integer_value(cpus_count) >= 1),
    ?assertEqual(integer_value(wordsize) * 1024, integer_value(kiloword)),
    ?assertMatch({badarg, {?MODULE, integer_value, [bogus]}}, integer_value(bogus)),
    ?assertMatch({badarg, {?MODULE, integer_value, [_]}}, integer_value(3.14)).

-endif. % TEST
