name: Erlang CI

on: [push, pull_request]

jobs:

  build:
    name: OTP-${{ matrix.otp }} Rebar-${{ matrix.rebar }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-2022 ]
        otp: ['24', '26']
        rebar: ['3.22', '3.24']
        exclude:
          - otp: '24'
            os: macos-latest
          - rebar: '3.24'
            otp: '24'

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        id: install-erlang
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar }}

      - name: Compile
        run: rebar3 as prod do compile

      - name: EUnit Latin1
        env:
          ERL_FLAGS: '+pc latin1'
        run: rebar3 eunit

      - name: EUnit Unicode
        env:
          ERL_FLAGS: '+pc unicode'
        run: rebar3 eunit

      - name: XRef
        run: rebar3 as check do xref

      - name: Dialyzer
        run: rebar3 as check do dialyzer

      - name: EDoc
        run: rebar3 edoc
